#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "MMBasePRTDeviceDelegate.h"
#import "MMBluetoothDeviceModel.h"
#import "MMC1SDeviceDelegate.h"
#import "MMCDeviceDelegate.h"
#import "MMD1DeviceDelegate.h"
#import "MMDeviceDelegate.h"
#import "MMDeviceDelegateGenerator.h"
#import "MMDeviceDelegatePacket.h"
#import "MMDeviceManagerOpModel.h"
#import "MMDeviceProtocolDefine.h"
#import "MMGTDeviceDelegate.h"
#import "MMIBangDeviceDelegate.h"
#import "MMP2DeviceDelegate.h"
#import "MMP2SDeviceDelegate.h"
#import "MMP3DeviceDelegate.h"
#import "MMTDeviceDelegate.h"
#import "cpstool.h"
#import "lzoconf.h"
#import "lzodefs.h"
#import "minilzo.h"
#import "MMCompress.h"
#import "ImageManipulation.h"
#import "ImageProcessTool.h"
#import "CLAHE.h"
#import "HFMcoding.h"
#import "ImgCore.h"
#import "ImgFilter.h"
#import "ImgLineLSD.h"
#import "ImgOCRProc.h"
#import "ImgProc.h"
#import "ImgScanner.h"
#import "ImgSuctionSide.h"
#import "ImgTextFontSize.h"
#import "ImgTextForCutting.h"
#import "ImgTransform.h"
#import "ImgType.h"
#import "MMJ_ImgAlg.h"
#import "WM_DataEncode.h"
#import "MMImageLib.h"
#import "MMBLEDefines.h"
#import "MMBLEManager.h"
#import "MMBLENormalManager.h"
#import "MMPaperHoleModel.h"
#import "MMPaperLengthTool.h"
#import "MMPaperModel.h"
#import "phones.h"
#import "MMAlarmInfoModel.h"
#import "MMTimerManager.h"
#import "MMTimerModel.h"
#import "MMTimerNoteModel.h"
#import "MMTimerNoteSelectModel.h"
#import "MMTimerSyncTomatoModel.h"
#import "MMTimerTimeSynModel.h"
#import "MMTomatoInfoModel.h"
#import "MM_PRT_DEFINE.h"
#import "BLETransmissonModel.h"
#import "DBModelDeviceHistory.h"
#import "MMBLEConfig.h"
#import "MMDeviceInfoManager.h"
#import "MMNetworkManager.h"
#import "NSString+MMCategory.h"
#import "MMPrintCompressTool.h"
#import "NSArray+YYAdd.h"
#import "NSBundle+YYAdd.h"
#import "NSData+YYAdd.h"
#import "NSDate+YYAdd.h"
#import "NSDictionary+YYAdd.h"
#import "NSKeyedUnarchiver+YYAdd.h"
#import "NSNotificationCenter+YYAdd.h"
#import "NSNumber+YYAdd.h"
#import "NSObject+YYAdd.h"
#import "NSObject+YYAddForKVO.h"
#import "NSString+YYAdd.h"
#import "NSTimer+YYAdd.h"
#import "CALayer+YYAdd.h"
#import "YYCGUtilities.h"
#import "UIApplication+YYAdd.h"
#import "UIBarButtonItem+YYAdd.h"
#import "UIBezierPath+YYAdd.h"
#import "UIColor+YYAdd.h"
#import "UIControl+YYAdd.h"
#import "UIDevice+YYAdd.h"
#import "UIFont+YYAdd.h"
#import "UIGestureRecognizer+YYAdd.h"
#import "UIImage+YYAdd.h"
#import "UIScreen+YYAdd.h"
#import "UIScrollView+YYAdd.h"
#import "UITableView+YYAdd.h"
#import "UITextField+YYAdd.h"
#import "UIView+YYAdd.h"
#import "YYCategories.h"
#import "YYCategoriesMacro.h"
#import "NSObject+YYModel.h"
#import "YYClassInfo.h"
#import "YYModel.h"
#import "NSObject+YYAddForARC.h"
#import "NSThread+YYAdd.h"

FOUNDATION_EXPORT double MMBLEManagerVersionNumber;
FOUNDATION_EXPORT const unsigned char MMBLEManagerVersionString[];

